### ISSUE TITLE
提升一下体验流畅度

### ISSUE THREAD

**Issue by kenneth** [kenneth/mvmap-android#1]
1.列表页下拉时候，内容不要显示为空。正在载入的状态。
2.holo主题切换后，列表页加载有点慢。
3.黑暗主题详细页还未实现。
4.减少loading的等待时间，看是否可以加快一下。

**Comment by niusmallnan** [comment]
关于①，如果要完整功能的下拉刷新  必须得支持按时间线分页。
关于②③，客户端尽量优化
关于④，影响loading时间包括前端的解析和服务端响应，无法实现单方面优化。
